openapi: 3.0.0
info:
  title: MWAP Cloud Providers API
  version: 1.0.0
  description: API for managing cloud provider configurations

paths:
  /api/v1/cloud-providers:
    get:
      summary: List all cloud providers
      description: Returns a list of all available cloud providers
      tags:
        - Cloud Providers
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of cloud providers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CloudProviderResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '500':
          $ref: '#/components/responses/ServerError'
    
    post:
      summary: Create a new cloud provider
      description: Creates a new cloud provider configuration (SuperAdmin only)
      tags:
        - Cloud Providers
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCloudProviderRequest'
      responses:
        '201':
          description: Cloud provider created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudProviderResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '409':
          description: Cloud provider with this name or slug already exists
        '500':
          $ref: '#/components/responses/ServerError'

  /api/v1/cloud-providers/{id}:
    get:
      summary: Get cloud provider by ID
      description: Returns a specific cloud provider by ID
      tags:
        - Cloud Providers
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Cloud provider ID
      responses:
        '200':
          description: Cloud provider details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudProviderResponse'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          description: Cloud provider not found
        '500':
          $ref: '#/components/responses/ServerError'
    
    patch:
      summary: Update cloud provider
      description: Updates an existing cloud provider (SuperAdmin only)
      tags:
        - Cloud Providers
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Cloud provider ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateCloudProviderRequest'
      responses:
        '200':
          description: Cloud provider updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CloudProviderResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Cloud provider not found
        '409':
          description: Cloud provider with this name or slug already exists
        '500':
          $ref: '#/components/responses/ServerError'
    
    delete:
      summary: Delete cloud provider
      description: Deletes a cloud provider (SuperAdmin only)
      tags:
        - Cloud Providers
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: Cloud provider ID
      responses:
        '204':
          description: Cloud provider deleted successfully
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          description: Cloud provider not found
        '409':
          description: Cloud provider is in use by existing integrations
        '500':
          $ref: '#/components/responses/ServerError'

components:
  schemas:
    CloudProviderResponse:
      type: object
      properties:
        _id:
          type: string
          description: Unique identifier
        name:
          type: string
          description: Display name of the cloud provider
        slug:
          type: string
          description: URL-friendly identifier
        authUrl:
          type: string
          format: uri
          description: OAuth authorization URL
        tokenUrl:
          type: string
          format: uri
          description: OAuth token URL
        clientId:
          type: string
          description: OAuth client ID
        scopes:
          type: array
          items:
            type: string
          description: Available OAuth scopes
        grantType:
          type: string
          description: OAuth grant type
          default: authorization_code
        tokenMethod:
          type: string
          description: HTTP method for token endpoint
          default: POST
        metadata:
          type: object
          properties:
            icon:
              type: string
              description: Icon identifier
            color:
              type: string
              description: Brand color (hex)
            description:
              type: string
              description: Short description
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
      required:
        - _id
        - name
        - slug
        - authUrl
        - tokenUrl
        - clientId
        - scopes
    
    CreateCloudProviderRequest:
      type: object
      properties:
        name:
          type: string
          description: Display name of the cloud provider
          minLength: 3
          maxLength: 50
        slug:
          type: string
          description: URL-friendly identifier
          pattern: ^[a-z0-9-]+$
          minLength: 2
          maxLength: 20
        authUrl:
          type: string
          format: uri
          description: OAuth authorization URL
        tokenUrl:
          type: string
          format: uri
          description: OAuth token URL
        clientId:
          type: string
          description: OAuth client ID
        clientSecret:
          type: string
          description: OAuth client secret (will be encrypted)
        scopes:
          type: array
          items:
            type: string
          description: Available OAuth scopes
        grantType:
          type: string
          description: OAuth grant type
          default: authorization_code
        tokenMethod:
          type: string
          description: HTTP method for token endpoint
          default: POST
        metadata:
          type: object
          properties:
            icon:
              type: string
              description: Icon identifier
            color:
              type: string
              description: Brand color (hex)
            description:
              type: string
              description: Short description
      required:
        - name
        - slug
        - authUrl
        - tokenUrl
        - clientId
        - clientSecret
        - scopes
    
    UpdateCloudProviderRequest:
      type: object
      properties:
        name:
          type: string
          description: Display name of the cloud provider
          minLength: 3
          maxLength: 50
        slug:
          type: string
          description: URL-friendly identifier
          pattern: ^[a-z0-9-]+$
          minLength: 2
          maxLength: 20
        authUrl:
          type: string
          format: uri
          description: OAuth authorization URL
        tokenUrl:
          type: string
          format: uri
          description: OAuth token URL
        clientId:
          type: string
          description: OAuth client ID
        clientSecret:
          type: string
          description: OAuth client secret (will be encrypted)
        scopes:
          type: array
          items:
            type: string
          description: Available OAuth scopes
        grantType:
          type: string
          description: OAuth grant type
        tokenMethod:
          type: string
          description: HTTP method for token endpoint
        metadata:
          type: object
          properties:
            icon:
              type: string
              description: Icon identifier
            color:
              type: string
              description: Brand color (hex)
            description:
              type: string
              description: Short description
  
  responses:
    BadRequest:
      description: Bad request - invalid input
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    
    Unauthorized:
      description: Unauthorized - authentication required
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    
    Forbidden:
      description: Forbidden - insufficient permissions
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    
    ServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT